### ISSUE TITLE
Journey organisation 

### ISSUE THREAD

**Issue by NastiaKarvatska1801** [NastiaKarvatska1801/Journey#1]
We have to organise a trip to Berlin, Germany. 
I don't know how to find some information and servises.

**Comment by TheMicrosoftMan** [comment]
You can find the needed information using these sites:
- [dw.com](https://www.dw.com/de/themen/s-9077)
- [getyourguide](https://www.getyourguide.ru)

**Comment by NastiaKarvatska1801** [comment]
Where should I search for bus tickets?

**Comment by TheMicrosoftMan** [comment]
See them over [here](https://ecolines.net/ua/uk/propozicii/miznarodni/lviv-berlin)

**Comment by NastiaKarvatska1801** [comment]
Fixed.

**Comment by NastiaKarvatska1801** [comment]
I find the most suitable ones. Done.

**Comment by NastiaKarvatska1801** [comment]
@NastiaKarvatska1801 did the part of given job.
@TheMicrosoftMan is your work finished?

**Comment by TheMicrosoftMan** [comment]
@NastiaKarvatska1801 yes
