### ISSUE TITLE
Buy bus tickets on the website.🚌🚍

### ISSUE THREAD

**Issue by NastiaKarvatska1801** [NastiaKarvatska1801/Journey#2]
Buy tickets which are not expencive.

**Comment by TheMicrosoftMan** [comment]
What should be the price?

**Comment by NastiaKarvatska1801** [comment]
Around  8-13 Euro for one person. Search!

**Comment by TheMicrosoftMan** [comment]
I have found tickets for 7 Euro for 1 person. 
https://ecolines.net/ua/uk/propozicii/miznarodni/lviv-berlin
Should I book them?

**Comment by NastiaKarvatska1801** [comment]
Sure, the price is OK.

**Comment by TheMicrosoftMan** [comment]
In progress.
